### ISSUE TITLE
Request: please offer this as an Android Studio plugin

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [jzbrooks/vgo#34]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want to have a visual UI, on Android Studio, to be able to run it on the files there, including seeing before and after, that indeed it looks the same.

**Describe alternatives you've considered**
Maybe online tools do this.

**Additional context**
...

**Comment by jzbrooks** [comment]
Android Studio shows previews of vector drawables, so you could inspect the preview after running the tool from the command line (or the relevant Gradle task). The plugin shows you which files changed by default. The command line tool requires the `--stats` flag to do that.

The tool's designed to automate vector optimization in a similar way that AAPT optimizes other resources in your build. The expectation should be that distortions won't happen, but if they do, we'll fix the problem.

I'm not sure what value an Android Studio plugin would provide.

**Comment by AndroidDeveloperLB** [comment]
I don't see a way to filter to vectorDrawables only, sadly.
And there is no optimization feature either.
